apiVersion: ec2.aws.crossplane.io/v1alpha4
kind: RouteTable
metadata:
  name: cs-routetable
spec:
  forProvider:
    region: us-east-1
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: cp-internetgateway
    associations:
      - subnetIdRef:
          name: cp-subnet-1
      - subnetIdRef:
          name: cp-subnet-2
    vpcIdRef:
      name: cp-vpc
  providerConfigRef:
    name: default
