apiVersion: ec2.aws.crossplane.io/v1alpha4
kind: RouteTable
metadata:
  name: cp-routetable
spec:
  forProvider:
    region: eu-central-1
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: cp-internetgateway
    associations:
      - subnetIdRef:
          name: cp-subnet-1
      - subnetIdRef:
          name: cp-subnet-2
    tags:
      - key: Environment
        value: Production
      - key: Owner
        value: Pavan
      - key: Name
        value: cp-routetable
    vpcIdRef:
      name: cp-vpc
  providerConfigRef:
    name: default
