### s3 ###

apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: dm-s3-cp
spec:
  forProvider:
    acl: private
    locationConstraint: eu-central-1
    versioningConfiguration:
      status: Enabled
 