apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: cp-access-sg
spec:
  forProvider:
    region: eu-central-1
    vpcIdRef:
      name: cp-vpc
    groupName: cp-sg
    description: communication to local application Pods
    tags:
      - key: Environment
        value: Production
      - key: Name
        value: cp-access-sg
      - key: Owner
        value: Pavan

    ingress:
      - fromPort: 3306
        toPort: 3306
        ipProtocol: tcp
        ipRanges:
          - cidrIp: 0.0.0.0/0
  providerConfigRef:
    name: default
