apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: cp-subnet-1
spec:
  forProvider:
    region: eu-central-1
    availabilityZone: eu-central-1a
    cidrBlock: 192.168.1.0/24
    vpcIdRef:
      name: cp-vpc
    tags:
      - key: Environment
        value: Production
      - key: Name
        value: cp-subnet-1
      - key: Owner
        value: Pavan
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: default

---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: cp-subnet-2
spec:
  forProvider:
    region: eu-central-1
    availabilityZone: eu-central-1b
    cidrBlock: 192.168.2.0/24
    vpcIdRef:
      name: cp-vpc
    tags:
      - key: Environment
        value: Production
      - key: Name
        value: cp-subnet-2
      - key: Owner
        value: Pavan
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: default
