apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: cp-vpc
spec:
  forProvider:
    region: eu-central-1
    cidrBlock: 192.168.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    tags:
      - key: Environment
        value: Production
      - key: Name
        value: cp-vpc
      - key: Owner
        value: Pavan
      - key: Zemer
        value: nonsense
    instanceTenancy: default
  providerConfigRef:
    name: default
